version: "3.8"

services:
  nats:
    image: nats:2.9
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4222"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  python_app:
    build:
      context: ./python_app
    container_name: python_app
    ports:
      - "8000:8000"
    depends_on:
      - nats
    volumes:
      - ./python_app:/app
      - ./logs:/app/logs
    environment:
      - NATS_URL=nats://nats:4222
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  go_app:
    build:
      context: ./go_app
    container_name: go_app
    depends_on:
      - nats
    volumes:
      - ./go_app:/app
      - ./logs:/app/logs
    environment:
      - NATS_URL=nats://nats:4222
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
