version: "3.8"

services:
  nats:
    image: nats:2.9
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4222"]
      interval: 15s
      retries: 3
      start_period: 5s
      timeout: 5s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

  python_app:
    build:
      context: ./python_app
    container_name: python_app
    ports:
      - "8000:8000"
    depends_on:
      - nats
    volumes:
      - ./python_app:/app
    environment:
      - NATS_SERVER_URL=nats://nats:4222
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      retries: 3
      start_period: 5s
      timeout: 5s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.7'

  go_app:
    build:
      context: ./go_app
    container_name: go_app
    depends_on:
      - nats
    volumes:
      - ./go_app/logs:/app/logs
    environment:
      - NATS_ADDR=nats://nats:4222
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.7'
