services:
  nats:
    extends:
      file: docker/compose/base.yml
      service: nats

  python_app:
    extends:
      file: docker/compose/python.yml
      service: python_app

  go_app:
    extends:
      file: docker/compose/golang.yml
      service: go_app

  docs:
    extends:
      file: docker/compose/docs.yml
      service: docs
