site_name: Network Packet Analyzer
site_description: Документация по проекту анализа сетевых пакетов
site_author: Aslan Alibekov
repo_url: https://github.com/AlibekovAA/network-analyzer-nats
theme:
  name: material
  language: ru
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition

nav:
  - Главная: index.md
  - Архитектура: architecture.md
  - API: api.md
  - Конфигурация: configuration.md
  - Docker: docker.md
