services:
  docs:
    build:
      context: ../../docs
      dockerfile: Dockerfile
    container_name: docs
    ports:
      - "8001:8001"
    volumes:
      - ../../docs:/docs
    labels:
      com.docker.compose.watch: "true"
